// This file is automatically generated. Do not edit or check into version control.
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: avoid_classes_with_only_static_members
library;

import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:url_launcher_web/url_launcher_web.dart' as url_launcher_web;

// ignore: public_member_api_docs
void registerPlugins([Registrar? pluginRegistrar]) {
  final Registrar registrar = pluginRegistrar ?? webPluginRegistrar;
  url_launcher_web.UrlLauncherPlugin.registerWith(registrar);
  registrar.registerMessageHandler();
}
